spring.application.name=proyecto

spring.datasource.url=jdbc:h2:mem:solicitudesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.expiry=5
jwt.secret=MiClaveSecretaSuperSeguraParaJWT2026EnProgramacionAvanzadaUniquindio
default-users.users[0].username=admin@solicitudes.com
default-users.users[0].password=admin123
default-users.users[0].role=ADMIN
default-users.users[1].username=agente@solicitudes.com
default-users.users[1].password=agente123
default-users.users[1].role=USER

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
